SELECT
date
,country_code
,country_name
,aggregation_level
,new_confirmed
,new_deceased
,cumulative_confirmed
,cumulative_deceased
,cumulative_tested
,new_persons_vaccinated
,cumulative_persons_vaccinated
,new_persons_fully_vaccinated
,cumulative_persons_fully_vaccinated
,new_vaccine_doses_administered
,cumulative_vaccine_doses_administered
,population
,population_male
,population_female
,population_rural
,population_urban
,population_density
,human_development_index
,population_age_00_09
,population_age_10_19
,population_age_20_29
,population_age_30_39
,population_age_40_49
,population_age_50_59
,population_age_60_69
,population_age_70_79
,population_age_80_and_older
,gdp_usd
,gdp_per_capita_usd
,openstreetmap_id
,latitude
,longitude
,area_sq_km
,smoking_prevalence
,diabetes_prevalence
,infant_mortality_rate
,nurses_per_1000
,physicians_per_1000
,health_expenditure_usd
,out_of_pocket_health_expenditure_usd
,school_closing
,workplace_closing
,cancel_public_events
,restrictions_on_gatherings
,public_transport_closing
,stay_at_home_requirements
,restrictions_on_internal_movement
,international_travel_controls
,income_support
,debt_relief
,fiscal_measures
,international_support
,public_information_campaigns
,testing_policy
,contact_tracing
,emergency_investment_in_healthcare
,investment_in_vaccines
,facial_coverings
,vaccination_policy
,stringency_index
,average_temperature_celsius
,minimum_temperature_celsius
,maximum_temperature_celsius
,rainfall_mm
,snowfall_mm
,dew_point
,relative_humidity
,new_tested
,population_largest_city
,population_clustered
,human_capital_index
,area_rural_sq_km
,area_urban_sq_km
,life_expectancy
,adult_male_mortality_rate
,adult_female_mortality_rate
,pollution_mortality_rate
,comorbidity_mortality_rate
,mobility_retail_and_recreation
,mobility_grocery_and_pharmacy
,mobility_parks
,mobility_transit_stations
,mobility_workplaces
,mobility_residential
,hospital_beds_per_1000
,new_recovered
,cumulative_recovered
,elevation_m
,new_hospitalized_patients
,cumulative_hospitalized_patients
,new_intensive_care_patients
,cumulative_intensive_care_patients
FROM `dbt-lightdash-test.dbt_ncaa_demo.covid19_open_data`

